config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :subscriptions, :member => { :deliver => :post }
  map.resources :users
  map.resources :sessions
  map.login 'login', :controller => 'sessions', :action => 'new'
  map.logout 'logout', :controller => 'sessions', :action => 'destroy'

  

   map.root :controller => "users", :action => "new"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :subscriptions
  validates_presence_of :name, :email
  validates_email_format_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, :except => [:new, :create]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.deliver_registration_confirmation(@user)
      flash[:notice] = "Successfully registered"
      redirect_to :controller => "users", :action => "new"
    else
      render :action => 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  
  def update
    @user = User.find(params[:id])
      if @user.update_attributes(params[:user])
        flash[:notice] = 'User was successfully updated.'
        redirect_to users_path
      else
        render :action => "edit"
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'User was successfully destroyed.'
    redirect_to(users_url)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% form_for(@user) do |f| %>
	<%= f.error_messages %>
	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>
	<p>	
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>
	<% for subscription in Subscription.all %>
		<p class="check_box">
			<%= check_box_tag "user[subscription_ids][]", subscription.id, @user.subscriptions.include?(subscription) %>
			<%= subscription.name %><br />
	<% end -%>

	<p id="submit_button">	
		<br />
		<%= f.submit "Subscribe" %>
	</p>
<% end -%>		

app/views/users/edit.html.erb
<div class="users"><% form_for(@user) do |f| %>
	<%= f.error_messages %>
	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>
	<p>	
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>
	<% for subscription in Subscription.all %>
		<p>
			<%= check_box_tag "user[subscription_ids][]", subscription.id, @user.subscriptions.include?(subscription) %>
			<%= subscription.name %>
	<% end -%>
	<p>	
		<%= f.submit "Update" %>
	</p>
<% end -%>
</div>

app/views/users/index.html.erb
<div class="users">
<% for user in @users %>
<div class="users_list">
	<h3><%= user.name %></h3>
	<ul>
	<% for subscription in user.subscriptions %>
		<li><%= subscription.name %></li>
	<% end -%>
		<%= link_to 'Edit', edit_user_path(user) %>
		<%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %>
	</ul>
	</div>	
<% end -%>
<%= link_to 'New user', new_user_path %>
</div>

app/views/users/new.html.erb
<h2>Never forget to play the lottery again.</h2>
<div id="story">
	<div id="left_text">
		<h3>Email Reminders.</h3>
		<p>You choose which lottery you want to subscribe to and we will 
				send you an email reminder 8 hours before every draw.
		</p>
		<h3>Unique Random Numbers.</h3>
		<p>We will also add your personal batch of unique random numbers 
				to the email.
		</p>
		<h3>Totally Free.</h3>
		<p>The service is free and we promise never to sell your details 
		or send you spam. Unsubscribe to lotto-mail anytime.
		</p>
	</div>
	<%= image_tag("email.jpg", :border => 0) %>
</div>
<div id="new_user_form">
	<h3>Sign Up</h3>
	<%= render :partial => 'form' %>
</div>
<div id="lottery_numbers">
	<div id="lottery_numbers_content">
		<h3>Lottery Number Generator</h3>
		<p class="para_padding_bottom">Use our random number generators to pick your numbers.</p>
		<%= link_to image_tag("uk_lotto_button.gif", :border => 0), :controller => "lotto", :action => "new_lotto" %>
		<%= link_to image_tag("uk_thunderball_button.gif", :border => 0), :controller => "lotto", :action => "new_thunder" %>
		<%= link_to image_tag("euromillions_button.gif", :border => 0), :controller => "lotto", :action => "new_euro" %>
		<%= link_to image_tag("newyork_button.gif", :border => 0), :controller => "lotto", :action => "new_newyork" %>
		<%= link_to image_tag("usa_powerball_button.gif", :border => 0), :controller => "lotto", :action => "new_usa_powerball" %>
		<%= link_to image_tag("canada649_button.gif", :border => 0), :controller => "lotto", :action => "new_canada_649" %>
		<%= link_to image_tag("usa_mega_button.gif", :border => 0), :controller => "lotto", :action => "new_usamega" %>
		<%= link_to image_tag("irish_button.gif", :border => 0), :controller => "lotto", :action => "new_irish" %>
	</div>
</div>